// <auto-generated />
using System;
using FootTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootTrack.Migrations
{
    [DbContext(typeof(FootTrackContext))]
    partial class FootTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootTrack.Models.DogodekNaTekmi", b =>
                {
                    b.Property<int?>("IgralecId")
                        .HasColumnType("int");

                    b.Property<int>("TekmaId")
                        .HasColumnType("int");

                    b.Property<int>("St_Dogodka")
                        .HasColumnType("int");

                    b.Property<int>("Minuta")
                        .HasColumnType("int");

                    b.Property<string>("TipDogodka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IgralecId", "TekmaId", "St_Dogodka");

                    b.HasIndex("TekmaId");

                    b.ToTable("Dogodek_Na_Tekmi");
                });

            modelBuilder.Entity("FootTrack.Models.Drzava", b =>
                {
                    b.Property<int>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrzavaId"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrzavaId");

                    b.ToTable("Drzave");
                });

            modelBuilder.Entity("FootTrack.Models.Ekipa", b =>
                {
                    b.Property<int>("EkipaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EkipaId"));

                    b.Property<DateOnly>("Datum_Ustanovitve")
                        .HasColumnType("date");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kratica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadionId")
                        .HasColumnType("int");

                    b.HasKey("EkipaId");

                    b.HasIndex("StadionId");

                    b.ToTable("Ekipe");
                });

            modelBuilder.Entity("FootTrack.Models.EkipaVSezoni", b =>
                {
                    b.Property<int>("EkipaId")
                        .HasColumnType("int");

                    b.Property<int>("SezonaId")
                        .HasColumnType("int");

                    b.Property<int>("Goli")
                        .HasColumnType("int");

                    b.Property<int>("Porazi")
                        .HasColumnType("int");

                    b.Property<int>("Prejeti_Goli")
                        .HasColumnType("int");

                    b.Property<int>("Remi")
                        .HasColumnType("int");

                    b.Property<int>("Tocke")
                        .HasColumnType("int");

                    b.Property<int>("Zmage")
                        .HasColumnType("int");

                    b.HasKey("EkipaId", "SezonaId");

                    b.HasIndex("SezonaId");

                    b.ToTable("Ekipa_V_Sezoni");
                });

            modelBuilder.Entity("FootTrack.Models.Igralec", b =>
                {
                    b.Property<int>("IgralecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgralecId"));

                    b.Property<DateOnly>("Datum_Rojstva")
                        .HasColumnType("date");

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<int>("EkipaId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IgralecId");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("EkipaId");

                    b.ToTable("Igralci");
                });

            modelBuilder.Entity("FootTrack.Models.IgralecNaTekmi", b =>
                {
                    b.Property<int>("IgralecId")
                        .HasColumnType("int");

                    b.Property<int>("TekmaId")
                        .HasColumnType("int");

                    b.Property<bool>("Kapetan")
                        .HasColumnType("bit");

                    b.Property<bool>("ZacetnaPostava")
                        .HasColumnType("bit");

                    b.HasKey("IgralecId", "TekmaId");

                    b.HasIndex("TekmaId");

                    b.ToTable("Igralec_Na_Tekmi");
                });

            modelBuilder.Entity("FootTrack.Models.Krog", b =>
                {
                    b.Property<int>("KrogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KrogId"));

                    b.Property<int>("SezonaId")
                        .HasColumnType("int");

                    b.Property<int>("Stevilka")
                        .HasColumnType("int");

                    b.HasKey("KrogId");

                    b.HasIndex("SezonaId");

                    b.ToTable("Krogi");
                });

            modelBuilder.Entity("FootTrack.Models.Mesto", b =>
                {
                    b.Property<int>("MestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MestoId"));

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MestoId");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Mesta");
                });

            modelBuilder.Entity("FootTrack.Models.Sezona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Leto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TekmovanjeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TekmovanjeId");

                    b.ToTable("Sezone");
                });

            modelBuilder.Entity("FootTrack.Models.Sodnik", b =>
                {
                    b.Property<int>("SodnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SodnikId"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SodnikId");

                    b.ToTable("Sodniki");
                });

            modelBuilder.Entity("FootTrack.Models.SodnikTekma", b =>
                {
                    b.Property<int>("TekmaId")
                        .HasColumnType("int");

                    b.Property<int>("SodnikId")
                        .HasColumnType("int");

                    b.Property<string>("Vloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TekmaId", "SodnikId");

                    b.HasIndex("SodnikId");

                    b.ToTable("Sodniki_Tekma");
                });

            modelBuilder.Entity("FootTrack.Models.Stadion", b =>
                {
                    b.Property<int>("StadionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadionId"));

                    b.Property<DateTime>("Datum_Otvoritve")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapaciteta")
                        .HasColumnType("int");

                    b.Property<int>("MestoId")
                        .HasColumnType("int");

                    b.HasKey("StadionId");

                    b.HasIndex("MestoId");

                    b.ToTable("Stadioni");
                });

            modelBuilder.Entity("FootTrack.Models.Tekma", b =>
                {
                    b.Property<int>("TekmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TekmaId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DomacaEkipaId")
                        .HasColumnType("int");

                    b.Property<int>("GoliDomaci")
                        .HasColumnType("int");

                    b.Property<int>("GoliGosti")
                        .HasColumnType("int");

                    b.Property<int>("GostujocaEkipaId")
                        .HasColumnType("int");

                    b.Property<int>("KrogId")
                        .HasColumnType("int");

                    b.Property<int>("StadionId")
                        .HasColumnType("int");

                    b.HasKey("TekmaId");

                    b.HasIndex("DomacaEkipaId");

                    b.HasIndex("GostujocaEkipaId");

                    b.HasIndex("KrogId");

                    b.HasIndex("StadionId");

                    b.ToTable("Tekme");
                });

            modelBuilder.Entity("FootTrack.Models.Tekmovanje", b =>
                {
                    b.Property<int>("TekmovanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TekmovanjeId"));

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UporabnikId")
                        .HasColumnType("int");

                    b.HasKey("TekmovanjeId");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("UporabnikId");

                    b.ToTable("Tekmovanja");
                });

            modelBuilder.Entity("FootTrack.Models.Trener", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Formacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trenerji");
                });

            modelBuilder.Entity("FootTrack.Models.TrenerObdobje", b =>
                {
                    b.Property<int>("TrenerId")
                        .HasColumnType("int");

                    b.Property<int>("EkipaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Zacetek")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Konec")
                        .HasColumnType("datetime2");

                    b.HasKey("TrenerId", "EkipaId", "Zacetek");

                    b.HasIndex("EkipaId");

                    b.ToTable("Trenerji_Obdobje");
                });

            modelBuilder.Entity("FootTrack.Models.Uporabnik", b =>
                {
                    b.Property<int>("UporabnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UporabnikId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GesloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NajljubsaEkipaId")
                        .HasColumnType("int");

                    b.Property<string>("UporabniskoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UporabnikId");

                    b.HasIndex("NajljubsaEkipaId");

                    b.ToTable("Uporabniki");
                });

            modelBuilder.Entity("FootTrack.Models.DogodekNaTekmi", b =>
                {
                    b.HasOne("FootTrack.Models.Igralec", "Igralec")
                        .WithMany("Dogodki")
                        .HasForeignKey("IgralecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Tekma", "Tekma")
                        .WithMany("Dogodki")
                        .HasForeignKey("TekmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igralec");

                    b.Navigation("Tekma");
                });

            modelBuilder.Entity("FootTrack.Models.Ekipa", b =>
                {
                    b.HasOne("FootTrack.Models.Stadion", "Stadion")
                        .WithMany()
                        .HasForeignKey("StadionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadion");
                });

            modelBuilder.Entity("FootTrack.Models.EkipaVSezoni", b =>
                {
                    b.HasOne("FootTrack.Models.Ekipa", "Ekipa")
                        .WithMany("Sezone")
                        .HasForeignKey("EkipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Sezona", "Sezona")
                        .WithMany("Ekipe")
                        .HasForeignKey("SezonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipa");

                    b.Navigation("Sezona");
                });

            modelBuilder.Entity("FootTrack.Models.Igralec", b =>
                {
                    b.HasOne("FootTrack.Models.Drzava", "Drzava")
                        .WithMany("Igralci")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Ekipa", "Ekipa")
                        .WithMany("Igralci")
                        .HasForeignKey("EkipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drzava");

                    b.Navigation("Ekipa");
                });

            modelBuilder.Entity("FootTrack.Models.IgralecNaTekmi", b =>
                {
                    b.HasOne("FootTrack.Models.Igralec", "Igralec")
                        .WithMany("Tekme")
                        .HasForeignKey("IgralecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Tekma", "Tekma")
                        .WithMany("Igralci")
                        .HasForeignKey("TekmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igralec");

                    b.Navigation("Tekma");
                });

            modelBuilder.Entity("FootTrack.Models.Krog", b =>
                {
                    b.HasOne("FootTrack.Models.Sezona", "Sezona")
                        .WithMany("Krogi")
                        .HasForeignKey("SezonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sezona");
                });

            modelBuilder.Entity("FootTrack.Models.Mesto", b =>
                {
                    b.HasOne("FootTrack.Models.Drzava", "Drzava")
                        .WithMany("Mesta")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("FootTrack.Models.Sezona", b =>
                {
                    b.HasOne("FootTrack.Models.Tekmovanje", "Tekmovanje")
                        .WithMany("Sezone")
                        .HasForeignKey("TekmovanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tekmovanje");
                });

            modelBuilder.Entity("FootTrack.Models.SodnikTekma", b =>
                {
                    b.HasOne("FootTrack.Models.Sodnik", "Sodnik")
                        .WithMany("SodnikTekme")
                        .HasForeignKey("SodnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Tekma", "Tekma")
                        .WithMany("Sodniki")
                        .HasForeignKey("TekmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sodnik");

                    b.Navigation("Tekma");
                });

            modelBuilder.Entity("FootTrack.Models.Stadion", b =>
                {
                    b.HasOne("FootTrack.Models.Mesto", "Mesto")
                        .WithMany("Stadioni")
                        .HasForeignKey("MestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesto");
                });

            modelBuilder.Entity("FootTrack.Models.Tekma", b =>
                {
                    b.HasOne("FootTrack.Models.Ekipa", "DomacaEkipa")
                        .WithMany("DomaceTekme")
                        .HasForeignKey("DomacaEkipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Ekipa", "GostujocaEkipa")
                        .WithMany("GostTekme")
                        .HasForeignKey("GostujocaEkipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Krog", "Krog")
                        .WithMany("Tekme")
                        .HasForeignKey("KrogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Stadion", "Stadion")
                        .WithMany("Tekme")
                        .HasForeignKey("StadionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DomacaEkipa");

                    b.Navigation("GostujocaEkipa");

                    b.Navigation("Krog");

                    b.Navigation("Stadion");
                });

            modelBuilder.Entity("FootTrack.Models.Tekmovanje", b =>
                {
                    b.HasOne("FootTrack.Models.Drzava", "Drzava")
                        .WithMany("Tekmovanja")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Uporabnik", null)
                        .WithMany("Naj_Tekmovanja")
                        .HasForeignKey("UporabnikId");

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("FootTrack.Models.TrenerObdobje", b =>
                {
                    b.HasOne("FootTrack.Models.Ekipa", "Ekipa")
                        .WithMany("TrenerjiObdobja")
                        .HasForeignKey("EkipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootTrack.Models.Trener", "Trener")
                        .WithMany("Obdobja")
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipa");

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("FootTrack.Models.Uporabnik", b =>
                {
                    b.HasOne("FootTrack.Models.Ekipa", "NajljubsaEkipa")
                        .WithMany()
                        .HasForeignKey("NajljubsaEkipaId");

                    b.Navigation("NajljubsaEkipa");
                });

            modelBuilder.Entity("FootTrack.Models.Drzava", b =>
                {
                    b.Navigation("Igralci");

                    b.Navigation("Mesta");

                    b.Navigation("Tekmovanja");
                });

            modelBuilder.Entity("FootTrack.Models.Ekipa", b =>
                {
                    b.Navigation("DomaceTekme");

                    b.Navigation("GostTekme");

                    b.Navigation("Igralci");

                    b.Navigation("Sezone");

                    b.Navigation("TrenerjiObdobja");
                });

            modelBuilder.Entity("FootTrack.Models.Igralec", b =>
                {
                    b.Navigation("Dogodki");

                    b.Navigation("Tekme");
                });

            modelBuilder.Entity("FootTrack.Models.Krog", b =>
                {
                    b.Navigation("Tekme");
                });

            modelBuilder.Entity("FootTrack.Models.Mesto", b =>
                {
                    b.Navigation("Stadioni");
                });

            modelBuilder.Entity("FootTrack.Models.Sezona", b =>
                {
                    b.Navigation("Ekipe");

                    b.Navigation("Krogi");
                });

            modelBuilder.Entity("FootTrack.Models.Sodnik", b =>
                {
                    b.Navigation("SodnikTekme");
                });

            modelBuilder.Entity("FootTrack.Models.Stadion", b =>
                {
                    b.Navigation("Tekme");
                });

            modelBuilder.Entity("FootTrack.Models.Tekma", b =>
                {
                    b.Navigation("Dogodki");

                    b.Navigation("Igralci");

                    b.Navigation("Sodniki");
                });

            modelBuilder.Entity("FootTrack.Models.Tekmovanje", b =>
                {
                    b.Navigation("Sezone");
                });

            modelBuilder.Entity("FootTrack.Models.Trener", b =>
                {
                    b.Navigation("Obdobja");
                });

            modelBuilder.Entity("FootTrack.Models.Uporabnik", b =>
                {
                    b.Navigation("Naj_Tekmovanja");
                });
#pragma warning restore 612, 618
        }
    }
}
